[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
todo_list_app = "Gxe7RqLt34mPqzNW532UBsVGcTabnFtYNs8ca2G8HD1t"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/parrotdev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
